config/routes.rb
Myapp::Application.routes.draw do
  resources :clause_masters, except: [:show]
  get "home/index"
  get "home/minor"

  root to: 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clause_master.rb
class ClauseMaster < ApplicationRecord
  validates :name, :content, :note, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clause_masters_controller.rb
class ClauseMastersController < ApplicationController

  add_breadcrumb 'Clause Master', :clause_masters_path

  before_action :set_clause_master, only: [:edit, :update, :destroy]
  before_action :redirect_cancel

  def index
    @clause_masters = ClauseMaster.all
  end

  def new
    @clause_master = ClauseMaster.new
  end

  def edit
    add_breadcrumb 'Edit', :edit_clause_master_path
  end

  def create
    @clause_master = ClauseMaster.new(clause_master_params)

    respond_to do |format|
      if @clause_master.save
        format.html { redirect_to clause_masters_path, notice: 'Clause master was successfully created.' }
        format.json { render :show, status: :created, location: @clause_master }
      else
        format.html { render :new }
        format.json { render json: @clause_master.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @clause_master.update(clause_master_params)
        format.html { redirect_to clause_masters_path, notice: 'Clause master was successfully updated.' }
        format.json { render :show, status: :ok, location: @clause_master }
      else
        format.html { render :edit }
        format.json { render json: @clause_master.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @clause_master.destroy
    respond_to do |format|
      format.html { redirect_to clause_masters_path, notice: 'Clause master was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_clause_master
    @clause_master = ClauseMaster.find(params[:id])
  end

  def clause_master_params
    params.require(:clause_master).permit(:name, :content, :note, :status)
  end

  def redirect_cancel
    if params[:cancel] == "Cancel"
      redirect_to clause_masters_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @mainTitle = ""
    @mainDesc = ""
  end

  def minor
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clause_masters/_form.html.erb
<%= form_with(model: clause_master, local: true) do |form| %>
  <% if clause_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clause_master.errors.count, "error") %> prohibited this clause_master from being saved:</h2>

      <ul>
      <% clause_master.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :clauseID %><br />
    <%= form.text_field :id, disabled: true %>
  </div>

  <div class="field">
    <%= form.label :clause_name %><br />
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %><br />
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :note %><br />
    <%= form.text_field :note %>
  </div>

  <div class="actions">
    <%= form.submit "History", name: "history" %>
    <%= form.submit "Save" %>
    <%= form.submit "Cancel", name: "cancel" %>
  </div>
<% end %>

app/views/clause_masters/edit.html.erb
<%= button_to "Delete", @clause_master,
                      method: :delete,
                      data: { confirm: "Are you sure" } %>

<%= render 'form', clause_master: @clause_master %>

app/views/clause_masters/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to "Add new", new_clause_master_path %>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Clause name</th>
      <th>Note</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @clause_masters.each do |clause_master| %>
      <tr>
        <td><%= clause_master.id %></td>
        <td><%= clause_master.name %></td>
        <td><%= clause_master.note %></td>
        <td><%= clause_master.status %></td>
        <td><%= link_to 'Duplicate' %></td>
        <td><%= link_to 'Edit', edit_clause_master_path(clause_master) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clause_masters/new.html.erb
<h1>New Clause Master</h1>

<%= render 'form', clause_master: @clause_master %>

<%= link_to 'Back', clause_masters_path %>

app/views/clause_masters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_clause_master_path(@clause_master) %> |
<%= link_to 'Back', clause_masters_path %>

app/views/home/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <h1>
                    <%= @mainTitle %>
                </h1>
                <small>
                    <%= @mainDesc %>
                </small>
            </div>
        </div>
    </div>
</div>

app/views/home/minor.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <h1>
                    Simple example of second view
                </h1>
                <small>Configure in home_controller.rb as minor view.</small>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        Example text
    </div>
    <div>
        <strong>Copyright</strong> Example Company &copy; 2014-2017
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">Example user</strong>
                            </span> <span class="text-muted text-xs block">Example menu <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="#">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>
            <li class="<%= 'active' if current_page?('/') %>">
                <%= link_to "/" do %>
                <i class="fa fa-laptop"></i> <span class="nav-label">Main page</span>
                <% end %>
            </li>
            <li class="<%= 'active' if current_page?('/home/minor') %>">
                <%= link_to "/home/minor" do %>
                <i class="fa fa-desktop"></i> <span class="nav-label">Minor page</span>
                <% end %>
            </li>
        </ul>

    </div>
</nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" method="post" action="/">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search" />
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <a href="#">
                    <i class="fa fa-sign-out"></i> Log out
                </a>
            </li>
        </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>INSPINIA</title>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

</head>
<body>

    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        <%= render 'layouts/navigation' %>

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar' %>

            <div>
              <%= render_breadcrumbs %>
            </div>

            <!-- Main view  -->
            <%= yield %>

            <!-- Footer -->
            <%= render 'layouts/footer' %>

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

</body>
</html>